name: deployment
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Get dependencies
        run: npm ci
      - name: Lint application
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [linter]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Run tests
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm run test:unit
